### ISSUE TITLE
add explicit model run in test block

### ISSUE THREAD

**Issue by gidden** [conda-forge/message-ix-feedstock#17]
In the next release, we should explicitly run message to confirm all deps are installed correctly. This can replace [the platform test](https://github.com/conda-forge/message-ix-feedstock/blob/master/recipe/meta.yaml#L37) as it will include the platform test.

As discussed in #16, this test should look functionally like:

```
python -c 'import message_ix; message_ix.testing.make_westeros(solve=True)'
```

**Comment by khaeru** [comment]
In #18, we realized that this would require GAMS to be installed on the Azure CI worker, which it currently isn't.

**Comment by khaeru** [comment]
This is now handled as part of our streamlined GitHub Actions CI workflow; see https://github.com/iiasa/ixmp/issues/160#issuecomment-659006929.
