### ISSUE TITLE
version name

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/message-ix-feedstock#5]
So we can't use `-prerelease` in the version name, as we found out unpleasantly (https://github.com/conda-forge/staged-recipes/pull/5904#discussion_r189471112). But just releasing it as `1.0.0` when it's actually `1.0.0-prerelease` seems...not ideal. Can we name it `1.0.0rc1` or `1.0.0a1`?

**Comment by gidden** [comment]
I am fine with bumping the name to `rc1`, but I am curious how conda relates this to other names. E.g., is there timestamp checking in order to know `1.0.0rc1` should be overtaken by the eventual `1.0.0`?

**Comment by djsutherland** [comment]
Yes, it knows that `1.0.0rc1 < 1.0.0`.
